In [1]:
import numpy as np

In [2]:
# 定义数组 a，并手动给出初始值
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [10,11,12]])
a   # 显示 a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [3]:
a.ndim  # 数组的维度，即秩，亦即轴数

2

In [4]:
a.shape  # 数组各维的长度，如4行3列

(4, 3)

In [5]:
a.size   # 数组中元素的个数

12

In [6]:
# 通过 arange()初始化数组的值
b = np.arange(0,12)    
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [7]:
# 通过 reshape() 组织数组
b = b.reshape(3,4)  
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
# 数组的行列转置
c = b.T
c

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [9]:
# 各元素求平方
a ** 2

array([[  1,   4,   9],
       [ 16,  25,  36],
       [ 49,  64,  81],
       [100, 121, 144]], dtype=int32)

In [10]:
# 各对应元素相乘
a * c

array([[  0,   8,  24],
       [  4,  25,  54],
       [ 14,  48,  90],
       [ 30,  77, 132]])

In [11]:
# 数组相乘
a @ b 

array([[ 32,  38,  44,  50],
       [ 68,  83,  98, 113],
       [104, 128, 152, 176],
       [140, 173, 206, 239]])

注：设$A$为$m \times p$ 的矩阵，$B$为$p \times n$ 的矩阵，那么称$m \times n$的矩阵$C$为矩阵$A$与$B$的乘积，记作$C = A B$，其中矩阵$C$中的第 $i$ 行第 $j$ 列元素可以表示为：
$$
C_{ij} = \sum_{k=1}^pa_{ik}b_{kj} = a_{i1}b_{1j}+a_{i2}b_{2j}+...+a_{ip}b_{pj}
$$